// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: find_user_by_password.sql

package database

import (
	"context"
)

const findUserByPassword = `-- name: FindUserByPassword :one
SELECT id, created_at, updated_at, email, hashed_password FROM users WHERE hashed_password = $1
`

func (q *Queries) FindUserByPassword(ctx context.Context, hashedPassword string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByPassword, hashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
