// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: UserOwnsChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userOwnsChirp = `-- name: UserOwnsChirp :one
SELECT EXISTS (
  SELECT 1
  FROM chirps
  WHERE chirps.id = $1 and chirps.user_id = $2
)
`

type UserOwnsChirpParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UserOwnsChirp(ctx context.Context, arg UserOwnsChirpParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userOwnsChirp, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
